@hostname = http://localhost:8000

### Получить список событий (List)
GET {{hostname}}/event/
Content-Type: application/json

### Получить событие по ID (Retrieve)
GET {{hostname}}/event/5/
Content-Type: application/json

### Создать событие (Create)
POST {{hostname}}/event/
Content-Type: application/json

{
    "title": "Концерт в парке",
    "location": "Парк Горького",
    "date": "2025-06-10",
    "start_time": "19:00:00",
    "is_free": false,
    "ticket_price": 300.00
}

### Полное изменение события (Update — PUT)
PUT {{hostname}}/event/4/
Content-Type: application/json

{
    "title": "Москва2025",
    "location": "Москва",
    "date": "2025-05-25",
    "start_time": "12:10:00",
    "is_free": true,
    "ticket_price": null
}

### Удалить событие (Destroy)
DELETE {{hostname}}/event/4/
Content-Type: application/json
